examples
day09
	<example>
	self assert: (self new day09p1: 10 marble: 1618) = 8317.
	self assert: (self new day09p1: 13 marble: 7999) = 146373.
	self assert: (self new day09p1: 17 marble: 1104) = 2764.
	self assert: (self new day09p1: 21 marble: 6111) = 54718.
	self assert: (self new day09p1: 30 marble: 5807) = 37305.
	self assert: (self new day09p1:486   marble: 70833) = 373597.
	self assert: (self new day09p1:486   marble: 7083300) = 2954067253.
	